= OntoRelMap-review
PRISMA-ScR for ontology-based mapping processes

== Description

This contains the supplementary material for the PRISMA-ScR on ontology-based mapping processes.

Samuel Dussaul, Luc Lavoie, Jean-François Ethier and Christina Khnaisser
A scoping review on ontology-driven mapping processes in healthcare and beyond: requirements
and remaining challenges
Submitted to BMC Medical Informatics and Decision Making
Collection on Semantic interoperability.

== Repository content

This repository contains:

. The figures link:figures/[figures/]
. The scripts and resource files used in the literature review process, including search queries and the results of each database link:search/[search/]
. The PDV version of the evaluated papers link:selected-papers/[selected-papers/]

== Contact
For more information please contact :

Christina Khnaisser : Christina.Khnaisser@usherbrooke.ca + 
Samuel Dussault : Samuel.Dussault@usherbrooke.ca 

== Licenses

The software is licensed under
https://forge.gouv.qc.ca/licence/en/liliq-v1-1/#strong-reciprocity-liliq-r[LILIQ-R+ version 1.1]

The text and documentation is licensed under
https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Common CC BY SA]
